export const IDL = {
  version: '0.1.0',
  name: 'savings_ladder',
  metadata: {
  address: "4xgharpczryhKNFB9KpqhuCswggM6mdLve8epAr7k2Q7"
  instructions: [
    {
      name: 'createGroup',
      accounts: [
        { name: 'group', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'mint', isMut: false, isSigner: false },
        { name: 'authority', isMut: true, isSigner: true },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
        { name: 'rent', isMut: false, isSigner: false },
      ],
      args: [
        { name: 'name', type: 'string' },
        { name: 'targetAmount', type: 'u64' },
        { name: 'monthlyContribution', type: 'u64' },
        { name: 'durationMonths', type: 'u32' },
        { name: 'maxMembers', type: 'u32' },
      ],
    },
    { name: 'joinGroup', accounts: [
        { name: 'group', isMut: true, isSigner: false },
        { name: 'member', isMut: true, isSigner: false },
        { name: 'authority', isMut: true, isSigner: true },
        { name: 'systemProgram', isMut: false, isSigner: false },
      ], args: [] },
    { name: 'depositMonthly', accounts: [
        { name: 'group', isMut: true, isSigner: false },
        { name: 'member', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'authority', isMut: true, isSigner: true },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ], args: [{ name: 'amount', type: 'u64' }] },
    { name: 'distributeRewards', accounts: [
        { name: 'group', isMut: true, isSigner: false },
        { name: 'authority', isMut: false, isSigner: true },
      ], args: [{ name: 'amount', type: 'u64' }] },
    { name: 'claimReward', accounts: [
        { name: 'group', isMut: true, isSigner: false },
        { name: 'member', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'authority', isMut: false, isSigner: true },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ], args: [] },
    { name: 'unlockMicroloan', accounts: [
        { name: 'group', isMut: true, isSigner: false },
        { name: 'member', isMut: false, isSigner: false },
        { name: 'microloan', isMut: true, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'authority', isMut: true, isSigner: true },
        { name: 'systemProgram', isMut: false, isSigner: false },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ], args: [{ name: 'loanAmount', type: 'u64' }, { name: 'repaymentMonths', type: 'u32' }] },
    { name: 'repayMicroloan', accounts: [
        { name: 'group', isMut: true, isSigner: false },
        { name: 'microloan', isMut: true, isSigner: false },
        { name: 'member', isMut: false, isSigner: false },
        { name: 'vault', isMut: true, isSigner: false },
        { name: 'userTokenAccount', isMut: true, isSigner: false },
        { name: 'authority', isMut: true, isSigner: true },
        { name: 'tokenProgram', isMut: false, isSigner: false },
      ], args: [{ name: 'amount', type: 'u64' }] },
    { name: 'closeGroup', accounts: [
        { name: 'group', isMut: true, isSigner: false },
        { name: 'authority', isMut: false, isSigner: true },
      ], args: [] },
  ],
  accounts: [
    { name: 'Group', type: { kind: 'struct', fields: [
          { name: 'authority', type: 'publicKey' }, { name: 'name', type: 'string' },
          { name: 'targetAmount', type: 'u64' }, { name: 'monthlyContribution', type: 'u64' },
          { name: 'durationMonths', type: 'u32' }, { name: 'maxMembers', type: 'u32' },
          { name: 'totalMembers', type: 'u32' }, { name: 'totalAccumulated', type: 'u64' },
          { name: 'totalInterest', type: 'u64' }, { name: 'vault', type: 'publicKey' },
          { name: 'isActive', type: 'bool' }, { name: 'createdAt', type: 'i64' },
          { name: 'bump', type: 'u8' }, { name: 'vaultBump', type: 'u8' },
    ] } },
    { name: 'Member', type: { kind: 'struct', fields: [
          { name: 'group', type: 'publicKey' }, { name: 'authority', type: 'publicKey' },
          { name: 'totalDeposited', type: 'u64' }, { name: 'totalWithdrawn', type: 'u64' },
          { name: 'depositCount', type: 'u32' }, { name: 'joinDate', type: 'i64' },
          { name: 'isActive', type: 'bool' }, { name: 'bump', type: 'u8' },
    ] } },
    { name: 'MicroLoan', type: { kind: 'struct', fields: [
          { name: 'member', type: 'publicKey' }, { name: 'group', type: 'publicKey' },
          { name: 'authority', type: 'publicKey' }, { name: 'loanAmount', type: 'u64' },
          { name: 'remainingAmount', type: 'u64' }, { name: 'repaymentMonths', type: 'u32' },
          { name: 'interestRate', type: 'u32' }, { name: 'createdAt', type: 'i64' },
          { name: 'isActive', type: 'bool' }, { name: 'bump', type: 'u8' },
    ] } },
  ],
  errors: [
    { code: 6000, name: 'InvalidAmount', msg: 'Amount must be greater than zero' },
    { code: 6001, name: 'NameTooLong', msg: 'Group name exceeds 50 characters' },
    { code: 6002, name: 'InvalidDuration', msg: 'Duration must be between 1-36 months' },
    { code: 6003, name: 'InvalidMaxMembers', msg: 'Max members must be between 2-50' },
    { code: 6004, name: 'GroupInactive', msg: 'This group is no longer active' },
    { code: 6005, name: 'GroupFull', msg: 'This group has reached maximum capacity' },
    { code: 6006, name: 'MemberInactive', msg: 'Member is not active in this group' },
    { code: 6007, name: 'NoMembers', msg: 'Cannot distribute rewards with 0 members' },
    { code: 6008, name: 'InsufficientCycles', msg: 'Need at least 3 deposit cycles' },
    { code: 6009, name: 'LoanTooLarge', msg: 'Loan exceeds 5x savings' },
    { code: 6010, name: 'LoanInactive', msg: 'Loan is no longer active' },
    { code: 6011, name: 'OverRepayment', msg: 'Repayment exceeds remaining balance' },
    { code: 6012, name: 'Overflow', msg: 'Arithmetic overflow' },
    { code: 6013, name: 'Unauthorized', msg: 'Not authorized' },
  ],
};
